name = "Orbit"
license = "MIT"
licenselink = "//github.com/aerohub/hugo-orbit-theme/blob/master/LICENSE.md"
description = "Responsive Resume/CV Theme for Developers"
homepage = "//sushil11th.github.io/resume/"
tags = ["cv", "resume", "colour schemes"]
features = ["responsive", "colour schemes"]
min_version = 0.16

[author]
  name = "Sushil Kumar"
  homepage = "//github.com/sushil11th"

# If porting an existing theme
[original]
  name = "Sushil Kumar"
  homepage = "//sushil11th.github.io"
  repo = "//sushil11th.github.io"
